apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "baft.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
    - port: 4222
      targetPort: 4222
      name: client
    {{- if .Values.nats.monitoring }}
    - port: 8222
      targetPort: 8222
      name: monitoring
    {{- end }}
